name: Get Coverage

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Get coverage from develop
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          develop_coverage=$(gh api -H 'Accept: application/vnd.github.raw' 'repos/metamask/metamask-extension/contents/coverage.json' | jq -r ".coverage // 0")
          echo "The coverage on develop for metamask-extension is $develop_coverage%."
